In [34]:
from scipy import stats
from math import sqrt, ceil
import numpy as np

### Calculate size of test based on $\alpha$ and $\beta$

In [35]:
def calculateSizeOfTest(p0=0.16, p1=0.175, alpha=0.05, beta=0.2):
    stdev0 = sqrt((1-p0)*p0*2)
    stdev1 = sqrt((1-p1)*p1+(1-p0)*p0)
    z0 = stats.norm.ppf(1-alpha)
    z1 = stats.norm.ppf(beta)
    return 2 * ((z0*stdev0-z1*stdev1)/(p1-p0))**2

In [36]:
calculateSizeOfTest(0.16, 0.175, 0.025, 0.2) / 3250

5.834253069693138

In [37]:
calculateSizeOfTest(0.02, 0.023, 0.025, 0.2) / 3250

21.49482835370974

In [38]:
def experiment_size(p_null, p_alt, alpha = .05, beta = .20):
    """
    Compute the minimum number of samples needed to achieve a desired power
    level for a given effect size.
    
    Input parameters:
        p_null: base success rate under null hypothesis
        p_alt : desired success rate to be detected
        alpha : Type-I error rate
        beta  : Type-II error rate
    
    Output value:
        n : Number of samples required for each group to obtain desired power
    """
    
    # Get necessary z-scores and standard deviations (@ 1 obs per group)
    z_null = stats.norm.ppf(1 - alpha)
    z_alt  = stats.norm.ppf(beta)
    sd_null = np.sqrt(p_null * (1-p_null) + p_null * (1-p_null))
    sd_alt  = np.sqrt(p_null * (1-p_null) + p_alt  * (1-p_alt) )
    
    # Compute and return minimum sample size
    p_diff = p_alt - p_null
    n = ((z_null*sd_null - z_alt*sd_alt) / p_diff) ** 2
    return np.ceil(n)

In [41]:
experiment_size(0.16, 0.175, 0.025) * 2 / 3250

5.834461538461539

In [42]:
experiment_size(0.02, 0.023, 0.025) * 2 / 3250

21.495384615384616

### Homepage experiment

In [1]:
import pandas as pd

/home/randomwalk10/anaconda3/envs/aind/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
pd.read_csv("homepage-experiment-data.csv")

,Day,Control Cookies,Control Downloads,Control Licenses,Experiment Cookies,Experiment Downloads,Experiment Licenses
0,1,1764,246,1,1850,339,3
1,2,1541,234,2,1590,281,2
2,3,1457,240,1,1515,274,1
3,4,1587,224,1,1541,284,2
4,5,1606,253,2,1643,292,3
5,6,1681,287,3,1780,299,3
6,7,1534,262,5,1555,276,8
7,8,1798,331,12,1787,326,20
8,9,1478,223,30,1553,298,38
9,10,1461,236,32,1458,289,23
10,11,1478,240,35,1555,279,36
11,12,1529,228,23,1567,267,34
12,13,1700,273,30,1793,349,32
13,14,1668,286,35,1619,308,31
14,15,1822,306,33,1775,300,32
15,16,1463,234,31,1606,279,29
16,17,1573,252,32,1551,295,36
17,18,1603,260,33,1607,281,27
18,19,1596,263,29,1625,289,29
19,20,1817,320,35,1780,315,23
20,21,1602,271,38,1588,256,44
21,22,1743,277,29,1861,341,37
22,23,1631,249,26,1517,272,35
23,24,1489,241,29,1466,279,31
24,25,1529,226,34,1609,284,29
25,26,1612,276,36,1574,295,38
26,27,1760,291,42,1666,297,28
27,28,1548,271,38,1587,314,37
28,29,1781,254,33,1728,290,41